### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-actions-test#4]
If you are here to suggest an edit to your existing project that is displayed on our site. Copy and paste the raw content of the file in the projects directory that has your project name below this line. Edit the content as necessary(Do not remove/edit any of the keys on the left). Then submit this issue.

---

```yaml
# DELETE EVERYTHIN BELOW THIS LINE AND PASTE THE CONTENT OF YOUR FILE
---
identification: '288594239'
title: BallotNav
description: BallotNav is a tool that aims to help prevent disenfranchisement by providing reliable and up to date information on ballot drop off locations across the US. While some states have detailed information about ballot drop off locations, others leave it up to the local jurisdiction to publish that information. In some states, Counties, Towns, Parishes, etc, do not have websites, so there is no reliable online source for ballot drop off information. BallotNav was created to provide a reliable online resource about where to drop your ballot, hours, accessibility, etc. We do this by calling each Jurisdictional office provided by the secretary of state and confirming locations details.
image: /assets/images/projects/ballot-nav.png
alt: 'Person holding phone with ballot nav website on it.'
image-hero: /assets/images/projects/ballot-nav-hero.png
alt-hero: 'Map of the United States with each state and county outlined.'
leadership:
  - name: Mya Stark
    role:
    links:
      slack: 'https://hackforla.slack.com/team/UMC7AJLDV'
      github: 'https://github.com/myastark'
    picture: 'https://avatars.githubusercontent.com/myastark'
links:
  - name: GitHub
    url: 'https://github.com/hackforla/BallotNav'
  - name: Site
    url: 'http://ballotnav.org'
  - name: Slack
    url: 'https://hackforla.slack.com/archives/C0191KE1XB7'
  - name: Readme
    url: 'https://github.com/hackforla/ballotnav/blob/master/README.md'
  - name: Overview
    url: 'https://github.com/hackforla/product-management/blob/master/project-one-sheets/BallotNav-Project-One-Sheet.pdf'
looking:
  - category: UI/UX
    skill: UX Researcher
  - category: SEO/Marketing
    skill: Marketing, PR & Partnerships
  - category: SEO/Marketing
    skill: Fundraising
  - category: Content
    skill: Translators (Spanish especially)
location:
  - Remote
partner: Code for America, Other Brigades
visible: true
status: Active
vertical: 'Vote / Representation'
---


```
